[workspace]
members = ["xtask"]
resolver = "3"

[package]
name = "neo"
description = "NEO for macOS"
version = "0.0.1"
edition = "2024"
rust-version = "1.97"
authors = ["ACTUAL LTD."]
license = "AGPL-3.0-or-later"
publish = false

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "bc538def4545534201bbfcac4e95ac34ea6501b6" }
libneo = { git = "https://github.com/superneoai/libneo.git", rev = "40c8ef17ae1d204ae0eb7ad6498c113df224ea9a", default-features = false, features = [
  "gpui",
] }


[package.metadata.packager]
formats = ["app"]
out-dir = "dist"
product-name = "NEO"
description = "NEO for macOS"
copyright = "Copyright © 2026 ACTUAL LTD."
identifier = "com.superneo.neo"
resources = [
  { src = "LICENSE", target = "Legal/AGPL-3.0-or-later.txt" },
  { src = "packaging/generated/THIRD-PARTY-NOTICES.md", target = "Legal/THIRD-PARTY-NOTICES.md" },
]

[package.metadata.packager.macos]
minimum-system-version = "26.1"
info-plist-path = "packaging/Info.plist"
